[package]
name = "Scrap2Bot"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = "0.95.0"
image = "0.24"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
x11rb = { version = "0.12.0" }
rayon = "1.5"
rand = "0.8"
crossterm = "0.26"